### ISSUE TITLE
version 0.0.5 in npm include jetbrains files

### ISSUE THREAD

**Issue by bluthen** [webmodules/blob#20]
Kind of surprised there is a 0.0.5 version since it isn't a release in this repo. However 0.0.5 in npm include several development environment files. Shown in bold below.

$ tar -tzvf blob-0.0.5.tgz 
-rw-rw-rw- 0/0             533 1985-10-26 03:15 package/package.json
**-rw-rw-rw- 0/0             276 1985-10-26 03:15 package/.zuul.yml**
-rw-rw-rw- 0/0             274 1985-10-26 03:15 package/component.json
-rw-rw-rw- 0/0            2531 1985-10-26 03:15 package/index.js
-rw-rw-rw- 0/0            1083 1985-10-26 03:15 package/LICENSE
-rw-rw-rw- 0/0             218 1985-10-26 03:15 package/Makefile
-rw-rw-rw- 0/0             326 1985-10-26 03:15 package/README.md
**-rw-rw-rw- 0/0             469 1985-10-26 03:15 package/.idea/blob.iml**
**-rw-rw-rw- 0/0             128 1985-10-26 03:15 package/.idea/inspectionProfiles/profiles_settings.xml**
**-rw-rw-rw- 0/0            4796 1985-10-26 03:15 package/.idea/markdown-navigator.xml**
**-rw-rw-rw- 0/0             106 1985-10-26 03:15 package/.idea/markdown-navigator/profiles_settings.xml**
**-rw-rw-rw- 0/0             267 1985-10-26 03:15 package/.idea/modules.xml
-rw-rw-rw- 0/0             185 1985-10-26 03:15 package/.idea/vcs.xml
-rw-rw-rw- 0/0           16028 1985-10-26 03:15 package/.idea/workspace.xml**
-rw-rw-rw- 0/0            3391 1985-10-26 03:15 package/test/index.js

**Comment by amitport** [comment]
The latest code is in https://github.com/amitport/blob.

This repo seems to be abandoned

**Comment by bluthen** [comment]
@amitport 
Oh Thanks! The npm entry points here. Would this issue then be something to file in your fork?

https://www.npmjs.com/package/blob

**Comment by amitport** [comment]
Well, you could, but I never really intended to maintain this lib (The original owners seem to be long gone. Whoever is still using it should stop.. socketio is probably the main culprit).

Currently, I don't have time to properly test changes so I would not take responsibility for publishing a new (possibly-breaking) release unless it is a current security-critical issue.

**Comment by amitport** [comment]
just released blob@0.1.0. Also added esm support

**Comment by bluthen** [comment]
Thanks @amitport
